spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rememberapi_test
    username: rememberapi
    password: float123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-test.xml
